# permissions for end users to edit images.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: image-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: image-editor-role
rules:
- apiGroups:
  - oci-mirror.kubebuilder.io.oci-mirror.kubebuilder.io
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oci-mirror.kubebuilder.io.oci-mirror.kubebuilder.io
  resources:
  - images/status
  verbs:
  - get
