apiVersion: oci-mirror.kubebuilder.io.oci-mirror.kubebuilder.io/v1alpha1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: image
    app.kubernetes.io/instance: image-sample
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder
  name: image-sample
spec:
  # TODO(user): Add fields here
