apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-sync-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oci-sync-controller
  template:
    metadata:
      labels:
        app: oci-sync-controller
    spec:
      serviceAccountName: oci-sync-controller
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: oci-sync-controller
        image: mirror-controller:v1.0.2
---
apiVersion: v1
kind: Service
metadata:
  name: oci-sync-controller
spec:
  selector:
    app: oci-sync-controller
  ports:
  - port: 8080