---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-sync-controller
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oci-sync-controller
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oci-sync-controller
subjects:
- kind: ServiceAccount
  name: oci-sync-controller
  namespace: metacontroller 
roleRef:
  kind: ClusterRole
  name: oci-sync-controller
  apiGroup: rbac.authorization.k8s.io