apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mirrors.example.com
spec:
  group: example.com
  names:
    kind: Mirror
    plural: mirrors
    singular: mirror
  scope: Namespaced
  versions:
  - name: v1alpha
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              source:
                type: object
                properties:
                  registry:
                    type: string
                  image:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
              destination:
                type: object
                properties:
                  registry:
                    type: string
    subresources:
     status: {}
