apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mirrors.example.com
spec:
  group: example.com
  names:
    kind: Mirror
    plural: mirrors
    singular: mirror
  scope: Namespaced
  versions:
  - name: v1alpha
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              source:
                type: object
                properties:
                  registry:
                    type: string
                  image:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
              destination:
                type: object
                properties:
                  registry:
                    type: string
          status:
            type: object
            properties:
              source:
                type: string
              state:
                type: string
              lastSync:
                type: string
        required:
        - spec
    additionalPrinterColumns:
    - name: Source
      type: string
      description: Source registry address from which the image is mirrored
      jsonPath: .spec.source.registry
    - name: Image
      type: string
      description: Source image name
      jsonPath: .spec.source.image
    - name: Tags
      type: string
      description: Tags that are synced
      jsonPath: .spec.source.tags
    - name: Destination
      type: string
      description: Destination registry address
      jsonPath: .spec.destination.registry
    - name: State
      type: string
      description: Status of the sync
      jsonPath: .status.mirrored
    - name: LastSync
      type: date
      description: Last time the mirror was done
      jsonPath: .status.lastSync
    subresources:
     status: {}
