apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: oci-sync-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1alpha
    resource: mirrors
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://oci-sync-controller.metacontroller:8080/sync
